version: '3.8'

services:
  maxwell-signage-ui:
    image: ${DOCKER_REGISTRY-}maxwell-signage-ui
    build:
      context: ./maxwell-signage-ui
      dockerfile: Dockerfile
      network: host
    ports:
      - "4205:443"
    environment:
      - NODE_ENV=Development
      - CERT=pugWEB
      - KEY=pugWEBkey.pem
      - TEST1=fart
       command: >
            /bin/sh -c
            "envsubst '
            $${CERT}
            '< /etc/nginx/nginx.conf.template
            > /etc/nginx/nginx.conf
            && nginx -g 'daemon off;'"
    restart: always

    